import { useState } from "react";
import { useNavigate } from "react-router-dom";
import ErrorBanner from "../components/ErrorBanner";
import { createAsset } from "../services/assetService";
import type { MediaType, Visibility } from "../types/asset";

export default function Upload() {
  const navigate = useNavigate();

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [mediaType, setMediaType] = useState<MediaType>("image");
  const [mimeType, setMimeType] = useState("image/jpeg");
  const [fileName, setFileName] = useState("demo-file.jpg");
  const [blobUrl, setBlobUrl] = useState("https://placehold.co/900x600?text=HyMedia+Upload");
  const [tags, setTags] = useState("demo,hymedia");
  const [visibility, setVisibility] = useState<Visibility>("PUBLIC");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();

    try {
      setSaving(true);
      setError("");

      const response = await createAsset({
        title,
        description,
        mediaType,
        mimeType,
        fileName,
        blobUrl,
        tags,
        visibility,
        ownerId: "demo_user"
      });

      navigate("/assets/" + response.data.id);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create asset.");
    } finally {
      setSaving(false);
    }
  }

  function handleMediaTypeChange(value: MediaType) {
    setMediaType(value);

    if (value === "image") {
      setMimeType("image/jpeg");
      setFileName("demo-image.jpg");
      setBlobUrl("https://placehold.co/900x600?text=HyMedia+Image");
    }

    if (value === "video") {
      setMimeType("video/mp4");
      setFileName("demo-video.mp4");
      setBlobUrl("");
    }

    if (value === "audio") {
      setMimeType("audio/mpeg");
      setFileName("demo-audio.mp3");
      setBlobUrl("");
    }

    if (value === "gif") {
      setMimeType("image/gif");
      setFileName("demo-animation.gif");
      setBlobUrl("https://placehold.co/900x600?text=HyMedia+GIF");
    }
  }

  return (
    <section className="page">
      <div className="page-heading">
        <div>
          <h2>Upload Asset Metadata</h2>
          <p>
            Current stage creates metadata through the REST API. Actual Azure Blob
            file upload comes in the next backend stage.
          </p>
        </div>
      </div>

      {error && <ErrorBanner message={error} />}

      <form className="form-panel" onSubmit={handleSubmit}>
        <label>
          Title
          <input
            value={title}
            onChange={(event) => setTitle(event.target.value)}
            placeholder="Example: London Food Clip"
            required
          />
        </label>

        <label>
          Description
          <textarea
            value={description}
            onChange={(event) => setDescription(event.target.value)}
            placeholder="Describe this media asset..."
            rows={4}
          />
        </label>

        <div className="form-row">
          <label>
            Media Type
            <select
              value={mediaType}
              onChange={(event) => handleMediaTypeChange(event.target.value as MediaType)}
            >
              <option value="image">Image</option>
              <option value="video">Video</option>
              <option value="audio">Audio</option>
              <option value="gif">GIF</option>
            </select>
          </label>

          <label>
            Visibility
            <select
              value={visibility}
              onChange={(event) => setVisibility(event.target.value as Visibility)}
            >
              <option value="PUBLIC">Public</option>
              <option value="PRIVATE">Private</option>
              <option value="UNLISTED">Unlisted</option>
            </select>
          </label>
        </div>

        <div className="form-row">
          <label>
            MIME Type
            <input value={mimeType} onChange={(event) => setMimeType(event.target.value)} />
          </label>

          <label>
            File Name
            <input value={fileName} onChange={(event) => setFileName(event.target.value)} />
          </label>
        </div>

        <label>
          Blob URL / Placeholder URL
          <input
            value={blobUrl}
            onChange={(event) => setBlobUrl(event.target.value)}
            placeholder="Will be generated by Azure Blob Storage later"
          />
        </label>

        <label>
          Tags
          <input
            value={tags}
            onChange={(event) => setTags(event.target.value)}
            placeholder="cloud,azure,demo"
          />
        </label>

        <button className="button button-primary" disabled={saving} type="submit">
          {saving ? "Creating..." : "Create Asset"}
        </button>
      </form>
    </section>
  );
}
